### PR TITLE
Porting over the container

### PR DESCRIPTION
**Pull request by danielmarbach**
@seesharper here we go.

### CODE REVIEW

**Comment by seesharper** [comment]
Thanks @danielmarbach. :)

May I just ask what made you go with LightInject when choosing the default container?
Did the single internal file distribution have something to do with it?

**Comment by danielmarbach** [comment]
@seesharper 

We are in the process of enabling .NET core support with NServiceBus core. Previously we had ILmerged autofac as an internal container. ILmerging or repacking turned out to be more painful than giving benefits. We decided to look out for good IoC containers that ship as sources. We compared a bigger list and ended up with LightInject and DryIoc as good candidates. lightinject was easy to use, fast and we could get the code running pretty quickly. We also feel capable of maintaining the sources if at some point in time you'd be no longer maintaining it. Dryloc wasn't quite as lean. 

In the future we will potentially even get rid of the internal container completely but that will take a while. Until then Lightinject is a perfect fit for us

**Comment by seesharper** [comment]
Thanks for your answer and I think what makes most sense to me is this:
"We also feel capable of maintaining the sources if at some point in time you'd be no longer maintaining it"
Something we all should consider when picking third party dependencies. Size and complexity really matters in this context. 
The philosophy behind LightInject has always been simplicity, excellent performance and the ability to just include the whole thing as a single internal file. I have also used ILMerge on a few projects and it does not come entirely without issues and added complexity. 

I will create a new package from this repo(LightInject.NServiceBus) and let you know when it is out in case you want to put that in the docs somewhere.

In the meantime it would be nice if you could provide a link to LightInject in the NServiceBus readme.md file :)

**Comment by danielmarbach** [comment]
Ping me when the package is available. I will then write the doco PR for you and add it to the docs site.  

I added a PR to bring the license file into the repo https://github.com/seesharper/LightInject/pull/367
and here the readme update PR https://github.com/Particular/NServiceBus/pull/4828 Good catch by the way

**Pull request merged**
